name: Validate new subscriber
on: [pull_request]
jobs:
  validate-subscriber:
    name: "Validate new subscriber"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0
      - name: Checkout Pyodide Main
        run: git clone https://github.com/pyodide/pyodide.git
      - name: Get changed files
        id: changed-files
        run: |
          CHANGED_FILES=$(git diff --name-only origin/$GITHUB_BASE_REF...HEAD)

          ALL_CHANGED_FILES=$(echo "$CHANGED_FILES" | grep "^packages/.*\.json$" || echo "")

          echo "all_changed_files<<EOF" >> $GITHUB_OUTPUT
          echo "$ALL_CHANGED_FILES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      - name: Validate new subscriber files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            # Validate schema
            cat "$file" | pipx run jsonschema package-info.schema.json
            # Ensure PyPI exists
            pypi_name=$(jq ".packageName" "$file" --raw-output) 
            curl -s -o /dev/null -f "https://pypi.org/pypi/${pypi_name}/json"
            # Ensure pyodide knows about this package
            recipe_name=$(jq ".recipeName" "$file" --raw-output) 
            test -d "pyodide/packages/${recipe_name}"
          done
